FROM php:8.2-fpm


# Add environment variable
ARG DB_CONNECTION
ENV DB_CONNECTION=$DB_CONNECTION

ARG DB_HOST
ENV DB_HOST=$DB_HOST

ARG DB_PORT
ENV DB_PORT=$DB_PORT

ARG DB_DATABASE
ENV DB_DATABASE=$DB_DATABASE

ARG DB_USERNAME
ENV DB_USERNAME=$DB_USERNAME

ARG DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y \
    libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql

COPY . .

CMD php artisan serve --host=0.0.0.0 --port=8000
